### ISSUE TITLE
Install Metrics Server in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-metrics-server#2]
# Install Metrics Server in IBM Cloud

This documentation will guide you on how to install Metrics Server on the IBM Cloud using the Kubernetes Service. Simple and effective.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105613779-c95f3380-5d92-11eb-8338-aa6d2ac98abe.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105613786-d4b25f00-5d92-11eb-80b7-4e6c90fd06ce.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105613791-e09e2100-5d92-11eb-950f-8acbc55bd51c.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105613796-e72c9880-5d92-11eb-8ccf-804be42b4091.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105613804-ed227980-5d92-11eb-88bb-c337ce798b74.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105613816-f3b0f100-5d92-11eb-833c-e55d16492296.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105613834-fad7ff00-5d92-11eb-9232-d35e5683c2b0.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![StoragePaid1](https://user-images.githubusercontent.com/70336951/105613838-03c8d080-5d93-11eb-9397-c7a8226cdaae.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _metrics-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105613843-0e836580-5d93-11eb-9196-eb112bef1d6a.PNG)

## Step 3: Install Metrics Server

* Click on the search section at the top of the main page, type Metrics Server, and click on it.

![metrics1](https://user-images.githubusercontent.com/70336951/105613849-1c38eb00-5d93-11eb-9241-f4f59a76d948.PNG)

* A new window opens, select the cluster and enter the name you want for the Metrics Server workspace, in this case, it will be called _metrics-example_, accept the terms and click on *Install*. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/metrics-server "here").

![metrics2](https://user-images.githubusercontent.com/70336951/105614025-7b4b2f80-5d94-11eb-95d1-3b76e51c6b52.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105613856-2c50ca80-5d93-11eb-9548-69178946e417.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105613859-3246ab80-5d93-11eb-8d04-fb725fc08b57.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105613864-396db980-5d93-11eb-909c-335660b983f2.PNG)

![test7](https://user-images.githubusercontent.com/70336951/105613865-3e326d80-5d93-11eb-96e4-f115daa6fadb.PNG)

* Once you have installed the terminal, open it, and type the following command. It will show you the workspaces of your cluster. You can see *metrics-example* is now active.

`$ kubectl get ns`

![metricstest1](https://user-images.githubusercontent.com/70336951/105613870-49859900-5d93-11eb-9690-1d1b932c748d.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![metricstest2](https://user-images.githubusercontent.com/70336951/105613873-53a79780-5d93-11eb-9c52-92dbe1e2ec79.PNG)

`$ kubectl get service -n NAME SERVICE`

![metricstest3](https://user-images.githubusercontent.com/70336951/105613878-5acea580-5d93-11eb-9d73-b3aded08fe19.PNG)

* Select the pod within your service using bash so you can check the installation from the terminal.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

* Select the pod within your service using bash so you can check the installation from the terminal.

![metricstest5](https://user-images.githubusercontent.com/70336951/105613887-6ae68500-5d93-11eb-8589-35ef43e54b68.PNG)

* You can now use the Metrics Server to its API to read the Kubernetes Cluster metrics. You can edit the configuration file to fine tune and adjust what you need. You can read more about it [here](https://cloud.ibm.com/docs/containers?topic=containers-kernel "here").

`$ kubectl edit configmap metrics-server-config -n kube-system`

![metricstest6](https://user-images.githubusercontent.com/70336951/105613891-733ec000-5d93-11eb-81c8-51247fb71c79.PNG)

You have finished the installation, enjoy your Metrics Server Installation.

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
