### ISSUE TITLE
ARM Image missing

### ISSUE THREAD

**Issue by autarchprinceps** [bitnami/bitnami-docker-metrics-server#4]
There is no ARM version of this image. It is litterally the last image in our EKS cluster, that doesn't support ARM instances yet. Could you please enable multi arch build. I know other bitnami images have been build that way.

**Comment by rafariossaa** [comment]
Hi,
  I am sorry, but currently we are not creating ARM images, it is our roadmap, but I could not give an ETA.
 The only multi arch image is `minideb`.
