### ISSUE TITLE
Daily releases?

### ISSUE THREAD

**Issue by tompatib** [bitnami/bitnami-docker-metrics-server#5]
**Description**

I'm just wondering why there are daily releases and new docker image created where the only change is the release number but no underlying assets are changed. Shouldn't we have here a change detection?

**Steps to reproduce the issue:**

Bitnami bot is creating a a daily release it seems with rX number changed only. Also this affect to changes in the freezed releases like 0.5.0.

**Describe the results you expected:**

New release to be made only when there is a change. I might be wrong but this seems weird, can you please explain this?

**Comment by marcosbc** [comment]
Hi, these are some of the reasons why we decided to perform daily releases:

* The container image includes the latest versions of all system packages (from the base image).
* It contains the latest version of the application.
* The image contains the latest version of all application initialization/setup scripts.
* The pipeline is healthy. For instance, it allows us to detect breaking changes to metadata/scripts for the same image. Or even the functionality of the pipeline itself to build/test/push images.
* It is a lot simpler to implement. For instance, there are alternatives like change detection, but it would make much harder to detect issues not directly related to changes in libraries and component versions.

Is there any reason why this is a concern for you? Note that we recommend the usage of immutable tags, not rolling tags, in production environment. Read more about this [here](https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/).

**Comment by tompatib** [comment]
Thanks for the explanation @marcosbc. This is more clear now, I was just always wondering if I have xxxx-r4 version and there is already r35 available should I upgrade or not and in the meantime I just saw version updates in the PRs.
